### ISSUE TITLE
deck2pdf to export presenter notes to pdf

### ISSUE THREAD

**Issue by speendo** [regebro/hovercraft#69] opened 2015-03-02 18:29 UTC
Hey!

deck2pdf works pretty well to export the presentation to pdf.

Is there a way to use this (or another) tool to export the presenter notes to pdf?

Thank you in advance!

**Comment by regebro** [comment] 2015-03-03 07:09
Currently not. I'll think about that if I can come up with something.

**Comment by regebro** [comment] 2016-10-24 22:15
Well, there could possibly be an alternative CSS style that shows the main screen at the top and the presenter text below, but that would only work if you don't do rotational positioning. And I'm not sure it would work anyway.

**Comment by yeyeto2788** [comment] 2019-10-30 14:01
@regebro, @JayZar21, @speendo Hello guys! Trying to organize the issues I have encountered that this issue seems to be a duplicate of this one #15 since this is the most updated one can we close the one?

**Comment by regebro** [comment] 2019-10-31 06:26
Nah, we'll keep #15 as it's more generic. I believe that with modern CSS we should be able to make presentations printable. It's a generic impress.js issue, really.

**Closed by regebro** 2019-10-31 06:26 UTC
Labels: enhancement
