### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by asdf23** [regebro/hovercraft#70] opened 2015-03-15 18:57 UTC
I'm new to hovercraft, so forgive me if these already exists..

On another popular prenation tool there is a feature to blank the screen (in white or black). I find this very helpful when giving a presentation. I think b and w do this.

it would also be nice to have a background or outline for each slide. 

if I could skip ahead +2 slides by typing +<number> or -<number>. Also if I could go to a specific slide perhaps :<number> that would also be very helpful. 

One last thing.. if I could set a timeout so that the presentation could run itself and perhaps in a loop. And in such a way that a user could click a button to skip ahead (think of a second person story click X to eat the fruit, click Y to run away...)

As is this software will be very useful in my next presentation, thank you

**Comment by regebro** [comment] 2015-03-15 19:43
Background or outline can be done with CSS styling.

The other requests are doable, but I don't have time to implement them right now, maybe later.

**Comment by regebro** [comment] 2016-10-24 22:13
Closing as this now is a duplicate of the new issues.

**Closed by regebro** 2016-10-24 22:13 UTC
Labels: enhancement
